spring:
  profiles:
    active: dev

---

server:
  port: 8081

name: xh

enterprise:
  name: aa
  age: 20
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
---

name: xh
enterprise:
  name: aa
  age: 20
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 8082

---

name: xh
enterprise:
  name: aa
  age: 20
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8083

---
